export const FILTER_VISIBILITY = 'FILTER_VISIBILITY';
export const SEARCHBAR_INPUT = 'SEARCHBAR_INPUT';
export const FRESH_SEARCH = 'FRESH_SEARCH';
export const INFINITE_SCROLL_SEARCH = 'INFINITE_SCROLL_SEARCH';
export const FETCH_SEARCH_BEGIN = 'FETCH_SEARCH_BEGIN';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';